### ISSUE TITLE
提供一份分享转存代码

### ISSUE THREAD

**Issue by MyZafkiel** [jsyzchen/pan#15]
[github地址](https://github.com/MyZafkiel/baidu)
common 文件定义了一些请求类实例 本来还想做token过期自动更新的代码还没写
share 定义了转存能用的上的所有代码(这些函数执行都不需要啥权限,百度说的分享接入权限应该是指的发布分享权限)

**Comment by jsyzchen** [comment]
> [github地址](https://github.com/MyZafkiel/baidu) common 文件定义了一些请求类实例 本来还想做token过期自动更新的代码还没写 share 定义了转存能用的上的所有代码(这些函数执行都不需要啥权限,百度说的分享接入权限应该是指的发布分享权限)

好的，收到，感谢，但目前官方已经关闭了第三方分享的能力，所以SDK暂时不加上该功能了
