### ISSUE TITLE
请教一下百度网盘MD5的算法

### ISSUE THREAD

**Issue by spzgy** [jsyzchen/pan#6]
百度网盘开放平台提供获取文件信息的接口，其中返回的md5值，与传统的MD5的结果不一致。
虽然结果都是32位，请问你知道百度网盘的md5是怎么算的吗？

**Comment by jsyzchen** [comment]
不好意思，这是保密的，不能对外透露

**Comment by spzgy** [comment]
> 不好意思，这是保密的，不能对外透露

想问一下，校验下载文件的完整性有什么好方法吗，
现在我能想到的只有比对文件大小了。

**Comment by jsyzchen** [comment]
可以上传的时候记录下文件md5，下载的时候再校验下

**Comment by landall** [comment]
这玩意网上遍地都是了，go和java的都有现成的代码。自己去搜吧，wwww
