### ISSUE TITLE
遇到大文件时经常报错 downloadPart failed (unexpected)

### ISSUE THREAD

**Issue by spzgy** [jsyzchen/pan#7]
想问一下，是不是被服务端限制了或禁止了？
是不是要开通VIP才能有更好的下载体验？
前面10个分片都能正常下载，从第11个分片开始就出错了。

/jsyzchen/pan@v0.0.7/utils/file/download.go:64: isSupportRange: true
/jsyzchen/pan@v0.0.7/utils/file/download.go:76: downloadPart
/jsyzchen/pan@v0.0.7/utils/file/download.go:86: TotalPart: 19
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[9]下载from:92318598 to:102576219
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[4]下载from:41030488 to:51288109
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[6]下载from:61545732 to:71803353
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[7]下载from:71803354 to:82060975
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[8]下载from:82060976 to:92318597
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[1]下载from:10257622 to:20515243
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[0]下载from:0 to:10257621
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[5]下载from:51288110 to:61545731
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[2]下载from:20515244 to:30772865
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[3]下载from:30772866 to:41030487
/jsyzchen/pan@v0.0.7/utils/file/download.go:120: 下载文件失败: unexpected EOF {7 71803354 82060975 [] }
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[10]下载from:102576220 to:112833841
/jsyzchen/pan@v0.0.7/utils/file/download.go:120: 下载文件失败: unexpected EOF {8 82060976 92318597 [] }
/jsyzchen/pan@v0.0.7/utils/file/download.go:170: 开始[11]下载from:112833842 to:123091463
/jsyzchen/pan@v0.0.7/utils/file/download.go:120: 下载文件失败: unexpected EOF {5 51288110 61545731 [] }

**Comment by jsyzchen** [comment]
已修复，更新下最新版本
