### ISSUE TITLE
error_msg":"app id is empty"

### ISSUE THREAD

**Issue by codyace** [jsyzchen/pan#8]
代码：
path := "/apps/go/Doc5.docx"
localFilePath := "/Users/cody/Downloads/Doc5.docx"
fileUploader := file.NewUploader(accessToken, path, localFilePath)
resp, err2 := fileUploader.Upload()
报错：
response[{"error_code":31024,"error_msg":"app id is empty","request_id"

**Comment by jsyzchen** [comment]
需要先在百度网盘开放平台申请接入，接入地址 https://pan.baidu.com/union/apply?from=header
